#Alter sysctl configuration for NAT 

- name: Set ip forwarding and reload sysctl file
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable sending of all IPv4 ICMP redirected packets on interface eth0
  sysctl:
    name: net.ipv4.conf.eth0.send_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: Increase size of connection tracking server (suggested for NAT servers)
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 131072
    sysctl_set: yes
    state: present
    reload: yes


