openvpn:
  tar_path: '/etc/openvpn/keys'
  key:
    ca_expire: 3650
    expire: 3650
    size: 1024
    country: 'R0'
    province: 'CJ'
    city: 'Cluj-Napoca'
    org: 'UTCN'
    email: 'patrica.szasz@endava.com'
    message_digest: 'sha265'
  client_prefix: 'vpn-prod'
  key_dir: '/etc/openvpn/keys'
  user_query: '*:*' 
  type: 'server'
  subnet: '10.8.0.0' 
  netmask: '255.255.0.0'
#can't define signing_ca_key as part of openvpn dict
##and reuse {{ openvpn.key.dir }} because it goes into recursive loop


#Client
openvpn_client:
  gateway: "vpn.{{ ansible_fqdn.split('.')[1:] | join('.') }}"
  client_cn: 'client'

#Server
openvpn_server:
  push_routes: []
  push_options: []

#config file
openvpn_config:
  user: 'nobody'
  group: 'nobody'
  local: "{{ ansible_default_ipv4.address }}"
  port: '1194'
  keepalive: '10 120'
  log: '/var/log/openvpn.log'
  push: nil
  script-security: 2
  up: '/etc/openvpn/server.up.sh'
  persist-key: ''
  persist-tun: ''
  comp-lzo: ''
  ca: "{{ openvpn_signing_ca_cert }}"
  key: "{{ openvpn.key_dir }}/server.key"
  cert: "{{ openvpn.key_dir }}/server.crt"
  dh: "{{ openvpn.key_dir }}/dh{{ openvpn.key.size}}.pem"
  crl-verify: '/etc/openvpn/crl.pem'

#interface configuration depending on type
openvpn_server_config: 
  server: '{{ openvpn.subnet }} {{ openvpn.netmask }}'
  dev: 'tun0'
  ifconfig-pool-persist: 'ips.txt'

openvpn_client_config:
  client: ''
  dev: 'tun0'
  
  

openvpn_signing_ca_key: "{{ openvpn.key_dir }}/ca.key"
openvpn_signing_ca_cert: "{{ openvpn.key_dir }}/ca.crt"


#both push routes and push options must be defined as array of strings
#e.g: openvpn_push_routes: ['route 192.168.10.0 255.255.255.0', 'route.....']
#openvpn_push_options: ['dhcp-option DNS 208.67.222.222', '......']
openvpn_client_config:
  client: ''
  dev: 'tun0'

#openvpn_gateway: "vpn.{{ ansible_fqdn.split('.')[1:] | join('.') }}"


