openvpn_key_ca_expire: 3650
openvpn_key_expire: 3650
openvpn_key_size: 1024
openvpn_key_country: 'US'
openvpn_key_province: 'CA'
openvpn_key_city: 'San Francisco'
openvpn_key_org: 'Fort Funston'
openvpn_key_email: 'admin@foobar.com'
openvpn_key_message_digest: 'sha256'

openvpn_client_prefix: 'vpn-prod'
openvpn_key_dir: '/etc/openvpn/keys'
openvpn_signing_ca_key: '/etc/openvpn/keys/ca.key'
openvpn_signing_ca_cert: '/etc/openvpn/keys/ca.crt'
openvpn_user_query: '*:*'

openvpn_config_proto: 'udp'
openvpn_config_port: '1194'

#server.conf variables
#
#
#
openvpn_push_routes: []
openvpn_push_options: []

openvpn_config:
  user: 'nobody'
  group: 'nobody'
  local: "{{ ansible_default_ipv4.address }}"
  proto: 'udp'
  port: '1194'
  keepalive: '10 120'
  log: '/var/log/openvpn.log'
  push: 'nil'
  script-security: 2
  up: '/etc/openvpn/server.up.sh'
  persist-key: ''
  persist-tun: ''
  comp-lzo: ''
  ca: "{{ openvpn_signing_ca_cert }}"
  key: "{{ openvpn_key_dir }}/server.key"
  cert: "{{ openvpn_key_dir }}/server.crt"
  dh: "{{ openvpn_key_dir }}/dh{{ openvpn_key_size}}.pem"
  crl-verify: '/etc/openvpn/crl.pem'

openvpn_server_config:
  openvpn_config_server: '{{ openvpn_subnet }} {{ openvpn_netmask }}'
  openvpn_config_dev: 'tun0'
  openvpn_config_ifconfig_pool_persist: 'ips.txt'

openvpn_client_config:
  openvpn_config_client: ''
  openvpn_config_dev: 'tun0'

