- name: Create keys directory
  file:
    path: "{{ openvpn_key_dir }}"
    state: directory
    owner: root
    group: root
    #recurse: yes
    mode: 0700

- name: Create /etc/openvpn/easy-rsa directory
  file:
    path: /etc/openvpn/easy-rsa
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Render openssl.cnf 
  template:
    src: openssl.cnf.j2
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    owner: root
    group: root
    mode: 0755

- name: Render pkitool config file
  template:
    src: pkitool.j2
    dest: /etc/openvpn/easy-rsa/pkitool
    owner: root
    group: root
    mode: 0755

- name: Render vars file
  template:
    src: vars.j2
    dest: /etc/openvpn/easy-rsa/vars
    owner: root
    group: root
    mode: 0755

- name: Render Rakefile
  template:
    src: Rakefile.j2
    dest: /etc/openvpn/easy-rsa/Rakefile
    owner: root
    group: root
    mode: 0755

- name: Render server.up.sh
  template:
    src: server.up.sh.j2
    dest: /etc/openvpn/server.up.sh
    owner: root
    group: root
    mode: 0755
  notify: restart openvpn

- name: Create /etc/openvpn/server.up.d
  file: 
    path: /etc/openvpn/server.up.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Render openssl.cnf in key_dir
  template: 
    src: openssl.cnf.j2
    dest: "{{ openvpn_key_dir }}/openssl.cnf"
    owner: root
    group: root
    mode: 0644

#Must use template instead of file (file does not create if not existing)
- name: Create index.txt
  template: 
    src: index.txt.j2
    dest: "{{ openvpn_key_dir }}/index.txt"
    owner: root
    group: root
    mode: 0600
    force: no

- name: Create {{ openvpn_key_dir }}/serial
  template:
    src: serial.j2
    dest: "{{ openvpn_key_dir }}/serial"
    force: no
    

- name: Create DH params
  command: openssl dhparam -out {{ openvpn_key_dir }}/dh{{ openvpn_key_size }}.pem {{ openvpn_key_size }} creates={{ openvpn_key_dir }}/dh{{ openvpn_key_size }}.pem
  become: true

- name: Openvpn init CA
  shell: |
    export KEY_CN="{{ openvpn_key_org }} CA"
    openssl req -batch -days {{ openvpn_key_ca_expire }} \
    -nodes -new -newkey rsa:{{ openvpn_key_size }} \
    -{{ openvpn_key_message_digest }} -x509 \
    -keyout {{ openvpn_signing_ca_key }} \
    -out {{ openvpn_signing_ca_cert }} -config {{ openvpn_key_dir }}/openssl.cnf
  args:
    creates: "{{ openvpn_signing_ca_cert }}"
  become: true

- name: Openvpn server key
  shell: |
    export KEY_CN='server'
    openssl req -batch -days {{ openvpn_key_expire }} \
    -nodes -new -newkey rsa:{{ openvpn_key_size }} -keyout {{ openvpn_key_dir }}/server.key \
    -out {{ openvpn_key_dir }}/server.csr -extensions server \
    -config {{ openvpn_key_dir }}/openssl.cnf && \
    openssl ca -batch -days {{ openvpn_key_ca_expire }} \
    -out {{ openvpn_key_dir }}/server.crt -in {{ openvpn_key_dir }}/server.csr \
    -extensions server -md {{ openvpn_key_message_digest }} -config {{ openvpn_key_dir }}/openssl.cnf
  args:
    creates: "{{ openvpn_key_dir }}/server.crt"
  become: true

- name: Fix permissions for keys
  file:
    path: "{{ keys }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ openvpn_signing_ca_key }}"
    - "{{ openvpn_key_dir }}/server.key"
  loop_control:
    loop_var: keys
  
- name: Generate crl
  shell: |
    export KEY_CN="{{ openvpn_key_org }} CA"
    openssl ca -config /etc/openvpn/easy-rsa/openssl.cnf -gencrl \
    -keyfile {{ openvpn_key_dir }}/server.key \
    -cert {{ openvpn_key_dir }}/server.crt \
    -out {{ openvpn_key_dir }}/crl.pem
  args:
    creates: "{{ openvpn_key_dir }}/crl.pem"
  become: true

- name: Render default server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644
  notify: restart openvpn

- name: Enable at boot
  service:
    name: openvpn@server.service
    enabled: yes
    state: started



